name: deploy

# Run on master & long lived version branches
on:
  push:
    branches:
      - master
      - branch-*
      - gh-actions-ci
  pull_request:
    branches:
      - master
      - branch-*

jobs:
  test:

    # Note: caching & java config copied from existing upstream master.yml workflow therefore this config may need
    # changing if upstream changes.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8' ]
        hadoop: [ 'hadoop-2.7' ]
        hive: [ 'hive-2.3' ]
    name: Test Spark - JDK${{ matrix.java }}/${{ matrix.hadoop }}/${{ matrix.hive }}
    steps:
      - uses: actions/checkout@master
        with:
          # Allow ./dev/run-tests.py to query git history to determine tests to run
          fetch-depth: 0
      # We split caches because GitHub Action Cache has a 400MB-size limit.
      - uses: actions/cache@v1
        with:
          path: build
          key: build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/com
          key: ${{ matrix.java }}-${{ matrix.hadoop }}-maven-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.hadoop }}-maven-com-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/org
          key: ${{ matrix.java }}-${{ matrix.hadoop }}-maven-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.hadoop }}-maven-org-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/net
          key: ${{ matrix.java }}-${{ matrix.hadoop }}-maven-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.hadoop }}-maven-net-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/io
          key: ${{ matrix.java }}-${{ matrix.hadoop }}-maven-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.hadoop }}-maven-io-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # See Makefile
      - name: R cache
        uses: actions/cache@v1
        with:
          path: ~/.local/share/renv
          key: renv-${{ hashFiles('dev/renv.lock') }}
          restore-keys: |
            renv-
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.local/share/venv/spark
          key: venv-spark-${{ hashFiles('dev/requirements.txt') }}
          restore-keys: |
            venv-spark-
      - name: Run tests
        # FIXME: ::debug statements are temporary as requested by GitHub support as part of ticket to resolve losing log
        # output
        run: |
          echo "::debug setting maven opts"
          export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=1g -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
          echo "::debug installing"
          make install
          echo "::debug checking dependencies"
          make test-dependencies
#          echo "::debug running test suite!"
#          make test
#          rm -rf ~/.m2/repository/org/apache/spark
